<?php
namespace USMS\Reports;

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Style\Color;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Alignment;

class ExcelTemplate {
    
    private $spreadsheet;
    private $sheet;
    private $title;
    private $module;
    private $metadata;
    private $currentRow;

    public function __construct($title, $module, $metadata = []) {
        // Check if library exists
        if (!class_exists('PhpOffice\PhpSpreadsheet\Spreadsheet')) {
            die("Error: PhpSpreadsheet library not found. Please run 'composer require phpoffice/phpspreadsheet'.");
        }

        $this->spreadsheet = new Spreadsheet();
        $this->sheet = $this->spreadsheet->getActiveSheet();
        $this->title = $title;
        $this->module = $module;
        $this->metadata = $metadata;

        $this->setupProperties();
        $this->setupHeader();
    }

    private function setupProperties() {
        $props = $this->spreadsheet->getProperties();
        $props->setCreator(SITE_NAME . " Export Engine");
        $props->setLastModifiedBy(SITE_NAME . " System");
        $props->setTitle($this->title);
        $props->setSubject($this->module);
        $props->setDescription("Official Export generated by " . SITE_NAME);
        $props->setKeywords("export, sacco, " . $this->module);
        $props->setCategory("System Reports");
    }

    private function setupHeader() {
        // Brand Colors
        global $theme;
        $primaryColor = isset($theme['primary']) ? str_replace('#', '', $theme['primary']) : '1B5E20'; 

        // 1. Title Row
        $this->sheet->mergeCells('A1:F1');
        $this->sheet->setCellValue('A1', strtoupper(SITE_NAME) . ' - ' . strtoupper($this->title));
        $this->sheet->getStyle('A1')->applyFromArray([
            'font' => [
                'bold' => true,
                'color' => ['argb' => Color::COLOR_WHITE],
                'size' => 14
            ],
            'fill' => [
                'fillType' => Fill::FILL_SOLID,
                'startColor' => ['argb' => $primaryColor]
            ],
            'alignment' => [
                'horizontal' => Alignment::HORIZONTAL_CENTER
            ]
        ]);

        // 2. Metadata Rows
        $row = 2;
        $user = isset($_SESSION['user_full_name']) ? $_SESSION['user_full_name'] : (
                isset($_SESSION['admin_name']) ? $_SESSION['admin_name'] : (
                isset($_SESSION['username']) ? $_SESSION['username'] : (
                isset($_SESSION['member_name']) ? $_SESSION['member_name'] : 'System'
        )));

        $details = [
            'Module' => $this->module,
            'Generated By' => $user,
            'Date' => date('d-M-Y H:i:s'),
        ];
        
        if (!empty($this->metadata['account_ref'])) $details['Account Ref'] = $this->metadata['account_ref'];
        if (!empty($this->metadata['currency'])) $details['Currency'] = $this->metadata['currency'];

        foreach ($details as $key => $val) {
            $this->sheet->setCellValue('A' . $row, $key);
            $this->sheet->setCellValue('B' . $row, $val);
            $this->sheet->getStyle('A' . $row)->getFont()->setBold(true);
            $row++;
        }
        
        // Add a spacer
        $this->currentRow = $row + 1;
    }

    public function addData($headers, $data) {
        $startRow = $this->currentRow;
        $colChar = 'A';
        
        global $theme;
        $primaryColor = isset($theme['primary']) ? str_replace('#', '', $theme['primary']) : '1B5E20';

        // Headers
        foreach ($headers as $h) {
            $this->sheet->setCellValue($colChar . $startRow, strtoupper($h));
            
            // Header Style
            $this->sheet->getStyle($colChar . $startRow)->applyFromArray([
                'font' => ['bold' => true, 'color' => ['argb' => Color::COLOR_WHITE]],
                'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => $primaryColor]],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER]
            ]);
            
            $colChar++;
        }
        
        // Border for header
        $lastCol = chr(ord($colChar) - 1);
        $this->sheet->getStyle("A$startRow:$lastCol$startRow")->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN);
        
        // Freeze Header
        $this->sheet->freezePane('A' . ($startRow + 1));

        // Data
        $dataRow = $startRow + 1;
        foreach ($data as $record) {
            $colChar = 'A';
            $recordValues = is_array($record) ? array_values($record) : [];
            
            foreach ($recordValues as $val) {
                // Ensure we don't go past Z (basic Excel column logic needed for >26 columns, but assuming <26 for now)
                // If colChar is past Z, Phpspreadsheet handles standard coordinate strings, but direct char increment stops at Z usually? 
                // Actually PHP char increment 'Z'++ is 'AA'. So this is safe.
                
                $this->sheet->setCellValue($colChar . $dataRow, $val);
                $colChar++;
            }
            $dataRow++;
        }

        // Auto-size columns
        // Note: For large datasets, autosize can be slow. Since we want "Universal", we keep it.
        $lastColIndex = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::columnIndexFromString($lastCol);
        for ($i = 1; $i <= $lastColIndex; $i++) {
            $columnID = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($i);
            $this->sheet->getColumnDimension($columnID)->setAutoSize(true);
        }

        $this->currentRow = $dataRow + 1;
        
        // Add Summary/Totals if available in metadata
        if (!empty($this->metadata['totals'])) {
             $this->sheet->setCellValue('A' . $this->currentRow, 'TOTAL VALUE');
             $this->sheet->setCellValue('B' . $this->currentRow, $this->metadata['totals']);
             $this->sheet->getStyle('A' . $this->currentRow . ':B' . $this->currentRow)->getFont()->setBold(true);
        }
    }

    public function download($filename) {
        $writer = new Xlsx($this->spreadsheet);
        
        // Clean output buffer
        if (ob_get_length()) ob_clean();

        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('Cache-Control: max-age=0');
        header('Expires: 0');
        header('Pragma: public');

        $writer->save('php://output');
        exit;
    }
}
