<?php
namespace USMS\Reports;

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Style\Color;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Alignment;

class ExcelFinancialTemplate {
    
    private $spreadsheet;
    private $sheet;
    private $title;
    private $module;
    private $metadata;
    private $currentRow;

    public function __construct($title, $module, $metadata = []) {
        // Check if library exists
        if (!class_exists('PhpOffice\PhpSpreadsheet\Spreadsheet')) {
            die("Error: PhpSpreadsheet library not found. Please run 'composer require phpoffice/phpspreadsheet'.");
        }

        $this->spreadsheet = new Spreadsheet();
        $this->sheet = $this->spreadsheet->getActiveSheet();
        $this->title = $title;
        $this->module = $module;
        $this->metadata = $metadata;

        $this->setupProperties();
        $this->setupHeader();
    }

    private function setupProperties() {
        $props = $this->spreadsheet->getProperties();
        $props->setCreator(SITE_NAME . " Financial Engine");
        $props->setLastModifiedBy(SITE_NAME . " System");
        $props->setTitle($this->title);
        $props->setSubject($this->module);
        $props->setDescription("Official Financial Export generated by " . SITE_NAME);
        $props->setKeywords("financial, sacco, export, " . $this->module);
        $props->setCategory("Financial Records");
    }

    private function setupHeader() {
        // Brand Colors
        $primaryColor = '1B5E20'; // Green
        $accentColor = 'F4C430'; // Gold

        // 1. Title Row
        $this->sheet->mergeCells('A1:F1');
        $this->sheet->setCellValue('A1', strtoupper(SITE_NAME) . ' - ' . strtoupper($this->title));
        $this->sheet->getStyle('A1')->applyFromArray([
            'font' => [
                'bold' => true,
                'color' => ['argb' => Color::COLOR_WHITE],
                'size' => 14
            ],
            'fill' => [
                'fillType' => Fill::FILL_SOLID,
                'startColor' => ['argb' => $primaryColor]
            ],
            'alignment' => [
                'horizontal' => Alignment::HORIZONTAL_CENTER
            ]
        ]);

        // 2. Metadata Rows
        $row = 2;
        $details = [
            'Module' => $this->module,
            'Generated By' => $_SESSION['username'] ?? 'System',
            'Date' => date('d-M-Y H:i:s'),
            'Account Ref' => $this->metadata['account_ref'] ?? 'N/A',
            'Currency' => 'KES'
        ];

        foreach ($details as $key => $val) {
            $this->sheet->setCellValue('A' . $row, $key);
            $this->sheet->setCellValue('B' . $row, $val);
            $this->sheet->getStyle('A' . $row)->getFont()->setBold(true);
            $row++;
        }
        
        // Add a spacer
        $this->currentRow = $row + 1;
    }

    public function addData($headers, $data) {
        $startRow = $this->currentRow;
        $colChar = 'A';

        // Headers
        foreach ($headers as $h) {
            $this->sheet->setCellValue($colChar . $startRow, strtoupper($h));
            
            // Header Style
            $this->sheet->getStyle($colChar . $startRow)->applyFromArray([
                'font' => ['bold' => true, 'color' => ['argb' => Color::COLOR_WHITE]],
                'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => '1B5E20']],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER]
            ]);
            
            $colChar++;
        }
        $lastCol = chr(ord($colChar) - 1);
        $this->sheet->getStyle("A$startRow:$lastCol$startRow")->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN);
        
        // Frozen Header
        $this->sheet->freezePane('A' . ($startRow + 1));

        // Data
        $dataRow = $startRow + 1;
        foreach ($data as $record) {
            $colChar = 'A';
            foreach ($record as $val) {
                $this->sheet->setCellValue($colChar . $dataRow, $val);
                $colChar++;
            }
            $dataRow++;
        }

        // Auto-size columns
        foreach (range('A', $lastCol) as $columnID) {
            $this->sheet->getColumnDimension($columnID)->setAutoSize(true);
        }

        $this->currentRow = $dataRow + 1;
        
        // Add Summary/Totals if available in metadata
        if (!empty($this->metadata['totals'])) {
             $this->sheet->setCellValue('A' . $this->currentRow, 'TOTALS');
             $this->sheet->setCellValue('B' . $this->currentRow, $this->metadata['totals']);
             $this->sheet->getStyle('A' . $this->currentRow . ':B' . $this->currentRow)->getFont()->setBold(true);
        }
    }

    public function download($filename) {
        $writer = new Xlsx($this->spreadsheet);
        
        // Clean output buffer
        if (ob_get_length()) ob_clean();

        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('Cache-Control: max-age=0');

        $writer->save('php://output');
        exit;
    }
}
?>
