import os
import re

def fix_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    # 1. DESTRUCTIVE CLEANUP of ALL previous injection patterns
    # Remove sidebar calls
    content = re.sub(r'<\?php \$layout->sidebar\(\);\s*\?>', '', content)
    # Remove topbar calls (including any with variables)
    content = re.sub(r'<\?php \$layout->topbar\(.*?\);\s*\?>', '', content)
    # Remove footer calls
    content = re.sub(r'<\?php \$layout->footer\(\);\s*\?>', '', content)
    
    # Remove wrapper div starts (even if nested)
    content = re.sub(r'<div class="d-flex\s*[^"]*">', '', content)
    content = re.sub(r'<div class="flex-fill\s*[^"]*">', '', content)
    content = re.sub(r'<div class="main-content-wrapper\s*[^"]*">', '', content)
    content = re.sub(r'<div class="container-fluid\s*px-4\s*py-4">', '', content)
    
    # Remove wrapper div ends and comments
    content = re.sub(r'</div>\s*<!--\s*/container-fluid\s*-->', '', content)
    content = re.sub(r'</div>\s*<!--\s*/main-content-wrapper\s*-->', '', content)
    content = re.sub(r'</div>\s*<!--\s*/d-flex\s*-->', '', content)
    
    # NEW: Fix the accidental string literalization of "\n"
    content = content.replace('\\n', '\n')
    
    # 2. REMOVE EXCESSIVE WHITESPACE generated by steps above
    content = re.sub(r'\n{3,}', '\n\n', content)

    # 3. RE-INJECT CANONICAL STRUCTURE
    
    # START: Directly after the header call
    header_pattern = r'(<\?php \$layout->header\([^)]*\);\s*\?>)'
    replacement_start = r'\1' + "\n" + r'<?php $layout->sidebar(); ?>' + "\n" + r'<div class="main-content-wrapper">' + "\n" + r'    <?php $layout->topbar($pageTitle ?? ""); ?>' + "\n" + r'    <div class="container-fluid px-4 py-4">'
    
    if re.search(header_pattern, content):
        content = re.sub(header_pattern, replacement_start, content, count=1)
        
    # END: Before the final closing PHP tag or at the end of content
    # We strip trailing whitespace first
    content = content.strip()
    
    # If the file ends with a PHP footer pattern or similar, we clean it up
    # We'll just append our clean footer block at the very end but BEFORE any closing body/html
    # Most pages don't have body/html closing, they rely on footer.php
    
    clean_footer = (
        "\n    </div> <!-- /container-fluid -->\n"
        "    <?php $layout->footer(); ?>\n"
        "</div> <!-- /main-content-wrapper -->\n"
    )
    
    # If the file ends with ?>, we append before it if we can, or just after.
    # Actually, many USMS pages end with ?> with no HTML after.
    # Our header call opens <body> so footer must close it if not in footer call.
    # LayoutManager::footer() usually handles the script loads.
    
    if content.endswith('?>'):
        # Just inject before the end
        content = content[:-2].strip() + clean_footer + "?>\n"
    else:
        content += clean_footer

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"Fixed: {filepath}")

def main():
    admin_dir = r"c:\xampp\htdocs\usms\admin\pages"
    # Files we manually touched and confirmed are excluded to avoid double-processing
    exclude = ["dashboard.php", "statements.php", "users.php", 
               "fix_layout_v2.py", "standardize_layout.py", "fix_layouts.py", 
               "flex_layouts.py", "stabilize_layout.py", "stabilize_layout_v2.py"]
               
    for filename in os.listdir(admin_dir):
        if filename.endswith(".php") and filename not in exclude:
            fix_file(os.path.join(admin_dir, filename))

if __name__ == "__main__":
    main()
