import os
import re

def fix_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    # 1. DESTRUCTIVE CLEANUP of ALL previous injection patterns
    # Remove sidebar calls
    content = re.sub(r'<\?php \$layout->sidebar\(\);\s*\?>', '', content)
    # Remove topbar calls
    content = re.sub(r'<\?php \$layout->topbar\(.*?\);\s*\?>', '', content)
    # Remove footer calls
    content = re.sub(r'<\?php \$layout->footer\(\);\s*\?>', '', content)
    
    # Remove wrapper div starts
    content = re.sub(r'<div class="d-flex\s*[^"]*">', '', content)
    content = re.sub(r'<div class="flex-fill\s*[^"]*">', '', content)
    content = re.sub(r'<div class="main-content-wrapper\s*[^"]*">', '', content)
    content = re.sub(r'<div class="container-fluid\s*px-4\s*py-4">', '', content)
    
    # Remove wrapper div ends and comments
    content = re.sub(r'</div>\s*<!--\s*/?container-fluid\s*-->', '', content)
    content = re.sub(r'</div>\s*<!--\s*/?main-content-wrapper\s*-->', '', content)
    content = re.sub(r'</div>\s*<!--\s*/?d-flex\s*-->', '', content)
    
    # Remove stray body/html closing tags (we will re-add them canonically)
    content = re.sub(r'</body>\s*</html>', '', content, flags=re.IGNORECASE)
    
    # Fix accidental string literalization of "\n"
    content = content.replace('\\n', '\n')
    
    # 2. REMOVE EXCESSIVE WHITESPACE generated by steps above
    content = re.sub(r'\n{3,}', '\n\n', content)
    
    # Trim trailing whitespace including random PHP tags at the very end
    content = content.strip()
    if content.endswith('?>'):
        content = content[:-2].strip()

    # 3. RE-INJECT CANONICAL STRUCTURE
    
    # START: Directly after the header call
    # We find the first occurrence of header call
    header_pattern = r'(<\?php \$layout->header\([^)]*\);\s*\?>)'
    replacement_start = r'\1' + "\n" + r'<?php $layout->sidebar(); ?>' + "\n" + r'<div class="main-content-wrapper">' + "\n" + r'    <?php $layout->topbar($pageTitle ?? ""); ?>' + "\n" + r'    <div class="container-fluid px-4 py-4">'
    
    if re.search(header_pattern, content):
        content = re.sub(header_pattern, replacement_start, content, count=1)
    
    # END: Ensure we close any lingering PHP block and then add the footer
    # We check if the content has more <?php than ?> (naive check)
    open_tags = content.count('<?php')
    close_tags = content.count('?>')
    
    if open_tags > close_tags:
        content += "\n?>"
    
    # Final cleanup of the very end to ensure no duplicate ?> or weirdness
    content = content.strip()
    if content.endswith('?>'):
        # It's now safely closed.
        pass
    else:
        # If it doesn't end with ?>, it means it was pure HTML at the end.
        pass

    clean_footer = (
        "\n    </div> <!-- /container-fluid -->\n"
        "    <?php $layout->footer(); ?>\n"
        "</div> <!-- /main-content-wrapper -->\n"
        "</body>\n"
        "</html>\n"
    )
    
    content += clean_footer

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"Fixed: {filepath}")

def main():
    admin_dir = r"c:\xampp\htdocs\usms\admin\pages"
    # Files we want to skip or have already fixed manually
    exclude = ["fix_layout_v2.py", "standardize_layout.py", "fix_layouts.py", 
               "flex_layouts.py", "stabilize_layout.py", "stabilize_layout_v2.py",
               "fix_v3_nuclear.py", "fix_v4_smart.py"]
               
    for filename in os.listdir(admin_dir):
        if filename.endswith(".php") and filename not in exclude:
            fix_file(os.path.join(admin_dir, filename))

if __name__ == "__main__":
    main()
